// Generated by CoffeeScript 1.8.0
(function() {
  var resizeTimer;

  window.Event = {};

  Event.$editor = null;

  Event.$selected = null;

  resizeTimer = false;

  Event.cellClicked = function(cell, x, y) {
    var $cell;
    $cell = $(cell);
    if (this.$selected !== null) {
      this.$selected.removeClass('selected');
    }
    this.$selected = $cell;
    this.$selected.html('<img src="img/number/b' + x + 1 + '.png" style="width:100%;height:100%;"/>');
    $cell.addClass('selected');
  };

  Event.windowResized = function() {
    View.resizeEditor(this.$editor);
  };

  Event.initialize = function($editor) {
    this.$editor = $editor;
    $(window).resize(function() {
      if (resizeTimer !== false) {
        clearTimeout(resizeTimer);
      }
      resizeTimer = setTimeout((function() {
        Event.windowResized();
      }), 200);
    });
    $editor.on('tap click', function(e) {
      var offset, pageX, pageY, px, py, target, w, w_9, x, y;
      e.preventDefault();
      offset = $editor.offset();
      w = $editor.width();
      w_9 = w / 9;
      pageX = e.type === 'tap' ? e.x : e.pageX;
      pageY = e.type === 'tap' ? e.y : e.pageY;
      px = pageX - offset.left;
      py = pageY - offset.top;
      x = Math.floor(px / w_9);
      y = Math.floor(py / w_9);
      target = document.getElementById('c' + x + y * 9);
      Event.cellClicked(target, x, y);
    });
  };

}).call(this);

//# sourceMappingURL=event.js.map
