// Generated by CoffeeScript 1.8.0
(function() {
  this.importJS = function(path) {
    document.write('<script type="text/javascript" src="' + path + '"></script>');
  };

}).call(this);

//# sourceMappingURL=import.js.map
