// Generated by CoffeeScript 1.8.0
(function() {
  var Preload;

  Preload = (function() {
    function Preload() {}

    Preload.preloadImage = function(path) {
      var img;
      img = document.createElement('img');
      img.setAttribute('src', path);
    };

    Preload.preloadImages = function(path) {
      return function(pathList) {
        var i;
        i = 0;
        while (i < pathList.length) {
          preloadImage(pathList[i]);
          i++;
        }
      };
    };

    return Preload;

  })();

  this.Preload = Preload;

}).call(this);

//# sourceMappingURL=preload-image.js.map
