// Generated by CoffeeScript 1.8.0
(function() {
  var initialize;

  (function() {
    importJS('js/sprintf.js');
    importJS('js/preload-image.js');
    importJS('js/model.js');
    importJS('js/view.js');
    importJS('js/event.js');
    this.$editor = null;
  })();

  initialize = function() {
    var $editor;
    $editor = $('#editor');
    View.initEditor($editor);
    Event.initialize($editor);
  };

  jQuery(function($) {
    initialize();
  });

}).call(this);

//# sourceMappingURL=script.js.map
