// Generated by CoffeeScript 1.8.0
(function() {
  this.sprintf = function(pattern, args) {
    return pattern.replace(/\#{([^{}]*)}/g, function(a, b) {
      var r;
      r = args[b];
      if (typeof r === 'string' || typeof r === 'number') {
        return r;
      } else {
        return a;
      }
    });
  };

  this.printf = function(pattern, args) {
    console.log(sprintf(pattern, args));
  };

  return;

}).call(this);

//# sourceMappingURL=sprintf.js.map
