// Generated by CoffeeScript 1.8.0
(function() {
  var View;

  View = (function() {
    function View() {}

    View.$editor = null;

    View.preloadImages = function() {
      var i, n;
      i = 0;
      while (i < 9) {
        n = i + 1;
        Preload.preloadImage('img/number/b' + n + '.png');
        Preload.preloadImage('img/number/br' + n + '.png');
        Preload.preloadImage('img/number/bb' + n + '.png');
        i++;
      }
    };

    View.resizeEditor = function($editor) {
      var w;
      w = $editor.width();
      $editor.height(w);
    };

    View.initEditor = function($editor) {
      var cell, container, x, y, _results;
      this.$editor = $editor;
      View.resizeEditor($editor);
      container = document.getElementById('cell_container');
      y = 0;
      _results = [];
      while (y < 9) {
        x = 0;
        while (x < 9) {
          cell = document.createElement('div');
          cell.setAttribute('id', "c" + (x + y * 9));
          cell.setAttribute('class', 'cell x' + x + ' y' + y);
          cell.setAttribute('data-pos', "" + (x + y * 9));
          container.appendChild(cell);
          x++;
        }
        _results.push(y++);
      }
      return _results;
    };

    return View;

  })();

  this.View = View;

}).call(this);

//# sourceMappingURL=view.js.map
